<a href="https://colab.research.google.com/github/SaranyaBayaneni/Machine-Learning/blob/main/Bayes_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [ ]:
df=pd.read_csv("iris.csv")
X,Y= df.iloc[:, 0:-1],df["Species"]
X_train, X_test, Y_train, Y_test = train_test_split( X, Y,
test_size=0.30)
gnb_model = GaussianNB()
gnb_model.fit(X_train, Y_train)
Y_pred_class=gnb_model.predict(X_test)
print(df)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
Y_pred_prob=gnb_model.predict_proba(X_test)
print((Y_pred_class==Y_test).sum()/Y_test.shape[0])
print(gnb_model.score(X_test,Y_test))
print(metrics.accuracy_score(Y_test,Y_pred_class))
print(metrics.confusion_matrix(Y_test,Y_pred_class))

0.8888888888888888
0.8888888888888888
0.8888888888888888
[[14  0  0]
 [ 0 13  4]
 [ 0  1 13]]
